apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hellomk-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
 rules:
 - http:
     paths:
     - path: /hellominikube/
       backend:
         serviceName: hellomk-service
         servicePort: app
